apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
      - name: backend-user
        image: docker.io/mutemipo/udagram-api-user
        ports:
        - containerPort: 80
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "400Mi"
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
