apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
        - image: docker.io/mutemipo/udagram-api-feed
          name: backend-feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "400Mi"
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]

